### ISSUE TITLE
Charles would like a `config.plist`

### ISSUE THREAD

**Issue by chug2k** [MDTGroup/Market#4]
Hey guys,

I'm playing around with featuring your app on our CoderSchool.vn website. Can you shoot me your config.plist so I can ~~steal your app and make millions~~ feature your app on our site?

**Comment by ngothanhtai** [comment]
Hi Charles,
Here they are :)
[Config.plist.zip](https://github.com/MDTGroup/Market/files/98986/Config.plist.zip)

**Comment by chug2k** [comment]
Wait, don't leave that here. Delete this issue now! =)
